### PR TITLE
add german names for austrian states

### PR DESCRIPTION
**Pull request by wkapga**
changes to

data/at_states_grid1.rda

German names of states, name of column is "Bundesland" = Austrian name of states

### CODE REVIEW

**Comment by stedy** [comment]
Can you please update this to be a csv file instead of an rda file?

**Comment by wkapga** [comment]
hmmm... where on the repo should the csv go? i see only .rda in /data ...

**Comment by hafen** [comment]
Grids are specified in another repository: https://github.com/hafen/grid-designer

**Comment by wkapga** [comment]
oh, that makes sense. 
will do
thanks

**Pull request closed without merging**
