### PR TITLE
Adding grid for New Zealand regions

### PR DESCRIPTION
**Pull request by pierreroudier**
Added NZ regions following discussions with  @peeyooshc on https://github.com/hafen/geofacet/issues/87

### CODE REVIEW

**Comment by hafen** [comment]
Could you provide the csv form of your grid as opposed to this PR? I manage the grids in this repository: https://github.com/hafen/grid-designer with the idea that this can serve as a more general resource outside of this R package. Then I have a script that automatically generates the `grid_docs.R`, `valid_grids.R`, etc. from there.

If you'd like, you can submit a PR to the grid-designer repository instead, or you can paste the csv here and I'll place it there.

**Comment by pierreroudier** [comment]
@hafen All good, I see you've integrated the grid, so probably no need for me to draft a PR.

**Comment by hafen** [comment]
Ah sorry I thought the grid supplied in #87 was different. If that grid is different and you'd like a it added as well, please reopen.

**Comment by peeyooshc** [comment]
code,name,row,col
Northland,Northland,1,5
Auckland,Auckland,2,6
Taranaki,Taranaki,3,5
Waikato,Waikato,3,6
Bay of Plenty,Bay of Plenty,3,7
Gisborne,Gisborne,3,8
Manawatu-Whanganui,Manawatu-Whanganui,4,6
Hawke's Bay,Hawke's Bay,4,7
Wellington,Wellington,5,6
Marlborough,Marlborough,8,4
Tasman,Tasman,8,3
Nelson,Nelson,7,4
Canterbury,Canterbury,9,3
Otago,Otago,10,2
West Coast,West Coast,9,2
Southland,Southland,10,1

**Pull request closed without merging**
